
package com.bxtel.webservice.dxgz;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-06-18T15:22:55.009+08:00
 * Generated source version: 2.7.11
 * 
 */
 
public class SpInterface_SpInterfacePort_Server{

    protected SpInterface_SpInterfacePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SpInterfaceImpl();
        String address = "http://114.135.113.20:8889/SpInterface";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new SpInterface_SpInterfacePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
