package com.bxtel.webservice.dxgz;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-06-18T15:22:55.004+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://www.suntektech.com", name = "spInterface")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SpInterface {

    @WebResult(name = "Result", targetNamespace = "http://www.suntektech.com", partName = "Result")
    @WebMethod(operationName = "RefreshUserInfo")
    public Result refreshUserInfo(
        @WebParam(partName = "RefreshUserInfoRequest", name = "RefreshUserInfoRequest")
        RefreshUserInfoRequest refreshUserInfoRequest
    );

    @WebResult(name = "syncResult", targetNamespace = "http://www.suntektech.com", partName = "syncResult")
    @WebMethod
    public SyncSPUserResult syncSPUserList(
        @WebParam(partName = "spUser", name = "spUser")
        SPUserModel spUser
    );

    @WebResult(name = "userOrderInfo", targetNamespace = "http://www.suntektech.com", partName = "userOrderInfo")
    @WebMethod
    public UserOrderInfoArray queryUserOrder(
        @WebParam(partName = "userInfo", name = "userInfo")
        UserInfo userInfo
    );

    @WebResult(name = "authenResult", targetNamespace = "http://www.suntektech.com", partName = "authenResult")
    @WebMethod
    public AuthenSPUserResult authenSPUser(
        @WebParam(partName = "authenInfo", name = "authenInfo")
        AuthenSPUserModel authenInfo
    );

    @WebResult(name = "syncResult", targetNamespace = "http://www.suntektech.com", partName = "syncResult")
    @WebMethod
    public SyncSPUserResult refreshUserOrder(
        @WebParam(partName = "userOrder", name = "userOrder")
        UserOrderModel userOrder
    );
}
